baseURL = "https://olincollege.github.io/pie-2022-03/4-circle/4circle/public"
languageCode = "en-us"
title = "4Circle"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs/pie-2022-03/4-circle/4circle/public'
  homepage_button_text = 'Learn More'
  homepage_intro = '4Circle is a Connect 4 Player built with Go and Arduino that can play against a human player on a physical board'
  homepage_image = '/images/cover.png'

  ## You can enable to add anchor links to header elements
  enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "4Circle is a robotic Connect 4 Player built with Go and Arduino"
    meta_og_title = "4Circle"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.app"
    meta_og_description = "4Circle is a robotic Connect 4 Player built with Go and Arduino"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
